### PR TITLE
oggvorbis: add codec

### PR DESCRIPTION
**Pull request by jfreymuth**
Seeking does not work yet, as described in zikichombo/codec#15

I am unsure about the semantics of the `Codec.Sniff` function, should it
- return true only if it can certainly decode the file, or
- return false only if it can certainly not decode the file?

### CODE REVIEW

**Comment by wsc1** [comment]
Sniff()  should return true if it thinks it can decode the file.

for codec.Codec, yes there are [other issues](https://github.com/zikichombo/codec/issues/3#issuecomment-419555634) too

Do you prefer to wait til codec.Codec is fixed?

**Comment by wsc1** [comment]
There are 2 PRS for your reference for next steps.

The first one is [in codec](https://github.com/zikichombo/codec/pull/16) and is a redo 
of codec.Codec attempting to address all known issues.  It was tested on a flac decoder, 
which is PR #4, the seeking decoder functionality was not tested but it is written with the intent of fixing the issues your brought up.

In case it all works, last questions: are you ok with adding the zc license header to the file in your PR?  Do you want to be listed in corresponding Authors?

**Comment by jfreymuth** [comment]
Tested offline, working.

The Sniff function currently only looks for the ogg container, this might collide with other file formats in the future; I will improve this when I have more time.

**Comment by wsc1** [comment]
Great.  I am taking the PR + non answer of question about license + limitation in time as OK to merge and add license headers.

We'll work on getting the tests in better shape over time.

Thanks!

**Pull request merged**
